services:
  - type: web
    name: smart-school-api
    env: python
    plan: free
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    buildCommand: "pip install -r requirements.txt"
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: da4mdjezu
      - key: CLOUDINARY_API_KEY
        value: 493281977135412
      - key: CLOUDINARY_API_SECRET
        value: P5xxU64uEjNZy6wITFM5pD5Qu54
