services:
  - type: web
    name: smart-school-api
    env: python
    startCommand: gunicorn app:app
    buildCommand: ""
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: da4mdjezu
      - key: CLOUDINARY_API_KEY
        value: 493281977135412
      - key: CLOUDINARY_API_SECRET
        value: P5xxU64uEjNZy6wITFM5pD5Qu54
